export const SET_PRODUCTS = 'SET_PRODUCTS'
export const ACCUMULATE_PRODUCTS = 'ACCUMULATE_PRODUCTS'
export const SET_RANDOM_PRODUCTS = 'SET_RANDOM_PRODUCTS'
export const ADD_TO_FAMILY_PRODUCTS = 'ADD_TO_FAMILY_PRODUCTS'
